site_name: "FEDORA Docs"

plugins:
  - search
  - mermaid2

extra_css:
  - stylesheets/mermaid.css

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo/fedora-logo.png
  favicon: assets/logo/favicon.png
  palette:
    - scheme: default
      primary: #015B77
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: #015B77
      accent: #015B77
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Data Space Overview:
      - Overview: overview/fedora-overview.md
      - Main Goal: overview/project-main-goal.md
    # - Innovation: overview/innovation.md
  - Harvesting:
      - Introduction: harvesting/introduction.md
      - Installation: harvesting/installation.md
      - How to harvest: harvesting/how-to-harvest.md
    # - Harvest mobilityDCAT-AP : harvesting/harvest-mobilitydcat-ap.md
  - AI Assistant:
      - Introduction: ai-assistant/introduction.md
      - RAG architecture: ai-assistant/architecture.md
      - User guide: ai-assistant/user-guide.md
  - Changelog: changelog.md
